[filters.SimTimeFromDatTime]
function = "SimTimeFromDatTime"

[filters.FixReversedRoadLinearLand]
function = "FixReversedRoadLinearLand"

[filters.MergeCriticalEventPositions]
function = "MergeCriticalEventPositions"

[rois.roi1]
type = "column"
columnname = "CriticalEventNum"

[metrics.ceStartPos]
function = "criticalEventStartPos"

[metrics.ceEndPos]
function = "criticalEventEndPos"