[project]
site_name = "Pydre documentation"
site_description = "Documentation for Pydre, a driving simulation data processing engine."
extra_css = ["stylesheets/extra.css"]
nav = [
  { "Pydre Overview" = "index.md" },
  { "Tutorial" = [
    "tutorial/getting_started.md",
    "tutorial/installation.md",
    "tutorial/basic_analysis.md",
    "tutorial/using_local_files.md",
    "tutorial/using_ducklake.md",
    "tutorial/setting_up_configuration_file.md",
    "tutorial/custom_metrics.md",
    "tutorial/justSetup.md"]},
  {"Reference" = [
    "reference/filters.md", 
    "reference/metrics.md", 
    "reference/metricStandards.md"]},
  {"Explanation" = [
    "explanation/execution.md",
    "explanation/project_files.md",
    "explanation/rois.md",
    "explanation/developernotes.md"]},
  {"Merge Tool" = "mergetool.md"},
  {"Contributing" = "contrib.md"}
]

[project.theme]
icon.logo = "lucide/car"
variant = "modern"

[project.theme.palette]
scheme = "OSU"
primary = "custom"
accent = "custom"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = false
show_root_heading = false
separate_signature = true
line_length = 100
show_signature_annotations = true
signature_crossrefs = true
filters = ["!^_"]